export const blogList = [
    {
      id: 4,
      title: 'ADVENTURE IN YOU',
      category: 'adventure',
      subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/graphic-design-trends.png',
    },
    {
      id: 5,
      title: 'Loaded BBQ Baked Potatoes',
      category: 'cooking',
      subCategory: ['bbq', 'food', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/make-it-personal.jpg',
    },
    {
      id: 6,
      title: 'Beyond the Beach',
      category: 'travel',
      subCategory: ['beaches', 'sea', 'holidays'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
    },
    {
      id: 7,
      title: 'Art & Perception',
      category: 'art',
      subCategory: ['skill', 'design', 'passion'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/Synthwave-Postmodern.jpg',
    },
    {
      id: 1,
      title: '7 CSS tools you should be using ',
      category: 'development',
      subCategory: ['frontend', 'ui/ux', 'design'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/designer-1.jpg',
    },
    {
      id: 2,
      title: 'Milan Places That Highlight The City',
      category: 'travel',
      subCategory: ['vacation', 'holidays', 'sight seeing'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/f67396fc3cfce63a28e07ebb35d974ac.jpg',
    },
    {
      id: 3,
      title: 'Online Shopping – An Alternative to Shopping in the Mall',
      category: 'shopping',
      subCategory: ['e-commerce store', 'clothing', 'shopping store'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/fQwuyKJ9qxjSbr6REcgtmW-1200-80.jpg',
    },
    {
      id: 8,
      title: 'ADVENTURE IN YOU',
      category: 'adventure',
      subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/graphic-design-trends.png',
    },
    {
      id: 9,
      title: 'Loaded BBQ Baked Potatoes',
      category: 'cooking',
      subCategory: ['bbq', 'food', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/make-it-personal.jpg',
    },
    {
      id: 10,
      title: 'Beyond the Beach',
      category: 'travel',
      subCategory: ['beaches', 'sea', 'holidays'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
    },
    {
      id: 11,
      title: 'Art & Perception',
      category: 'art',
      subCategory: ['skill', 'design', 'passion'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/Synthwave-Postmodern.jpg',
    },
    {
      id: 25,
      title: 'Loaded BBQ Baked Potatoes',
      category: 'cooking',
      subCategory: ['bbq', 'food', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/make-it-personal.jpg',
    },
    {
      id: 12,
      title: 'Beyond the Beach',
      category: 'travel',
      subCategory: ['beaches', 'sea', 'holidays'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
    },
    {
      id: 13,
      title: 'Art & Perception',
      category: 'art',
      subCategory: ['skill', 'design', 'passion'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/Synthwave-Postmodern.jpg',
    },
    {
      id: 14,
      title: 'ADVENTURE IN YOU',
      category: 'adventure',
      subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/graphic-design-trends.png',
    },
    {
      id: 15,
      title: 'Loaded BBQ Baked Potatoes',
      category: 'cooking',
      subCategory: ['bbq', 'food', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/make-it-personal.jpg',
    },
    {
      id: 16,
      title: 'Beyond the Beach',
      category: 'travel',
      subCategory: ['beaches', 'sea', 'holidays'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
    },
    {
      id: 17,
      title: 'Art & Perception',
      category: 'art',
      subCategory: ['skill', 'design', 'passion'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/Synthwave-Postmodern.jpg',
    },
    {
      id: 18,
      title: '7 CSS tools you should be using ',
      category: 'development',
      subCategory: ['frontend', 'ui/ux', 'design'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/designer-1.jpg',
    },
    {
      id: 19,
      title: 'Milan Places That Highlight The City',
      category: 'travel',
      subCategory: ['vacation', 'holidays', 'sight seeing'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/f67396fc3cfce63a28e07ebb35d974ac.jpg',
    },
    {
      id: 20,
      title: 'Online Shopping – An Alternative to Shopping in the Mall',
      category: 'shopping',
      subCategory: ['e-commerce store', 'clothing', 'shopping store'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/fQwuyKJ9qxjSbr6REcgtmW-1200-80.jpg',
    },
    {
      id: 21,
      title: 'ADVENTURE IN YOU',
      category: 'adventure',
      subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/graphic-design-trends.png',
    },
    {
      id: 22,
      title: 'Loaded BBQ Baked Potatoes',
      category: 'cooking',
      subCategory: ['bbq', 'food', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/make-it-personal.jpg',
    },
    {
      id: 23,
      title: 'Beyond the Beach',
      category: 'travel',
      subCategory: ['beaches', 'sea', 'holidays'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
    },
    {
      id: 24,
      title: 'Art & Perception',
      category: 'art',
      subCategory: ['skill', 'design', 'passion'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/Synthwave-Postmodern.jpg',
    },
    {
      id: 29,
      title: 'Loaded BBQ Baked Potatoes',
      category: 'cooking',
      subCategory: ['bbq', 'food', 'lifestyle'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/make-it-personal.jpg',
    },
    {
      id: 26,
      title: 'Beyond the Beach',
      category: 'travel',
      subCategory: ['beaches', 'sea', 'holidays'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
    },
    {
      id: 27,
      title: 'Art & Perception',
      category: 'art',
      subCategory: ['skill', 'design', 'passion'],
      description:
                    '    Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia. It is the world fifth-most populous country, with a population of almost 243 million people, and has the world second-largest Muslim population just behind Indonesia.',
      authorName: 'John Doe',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/Synthwave-Postmodern.jpg',
    },
  ];